### ISSUE TITLE
Generated markdown must have same section structure

### ISSUE THREAD

**Issue by zvr** [spdx/spec-parser#10]
No matter what the order of the sections in the input is, the generated markdown should always present the same one.

For example,
```
# Name
# Summary
# Description
# Metadata
# Shape (or Entries)
```

**Comment by zvr** [comment]
Same thing with all entries in `Metadata` section

**Comment by nirmal-suthar** [comment]
> ```
> # Name
> # Summary
> # Description
> # Metadata
> # Shape (or Entries)
> ```

What all fields could be optional? To be specific, it is compulsory to have Summary/Description/... section in Classes and same for the Properties and Vocab ?

**Comment by zvr** [comment]
Yes, I'd think so...
At some point we *need* to have Summaries and Descriptions; otherwise, for example, ISO-formatted documentation will not be able to be generated.

**Comment by zvr** [comment]
We can start by having all sections mandatory and in order

**Comment by zvr** [comment]
This can be closed, it has been implemented for a while
