### ISSUE TITLE
Provide clear license

### ISSUE THREAD

**Issue by mattiasgronlund** [spdx/spec-parser#115]
Hi,

This seems very useful, and I expect to be able to contribute.

But this being provided without being clearly open source licensed, it will be hard for me to contribute.

BR
  Mattias

**Comment by zvr** [comment]
?!?

Every single source file is marked as licensed under `Apache-2.0` license.

Why do you think this is "not clearly open source licensed"?

**Comment by mattiasgronlund** [comment]
Interesting, I did not realize the way of describing the licensing, using SPDX License Identifier in each file, which seems smart.
I am in no way enough knowledge in copyright laws, to understand if that is enough, that indirect reference should be enough, but what do I know.

I suppose the tight coupling with SPDX for this repo, makes it logical that SBOM related things is done differently, and possible just ahead of others.

But would adding a copy of https://github.com/spdx/tools-python/blob/main/LICENSE, providing hints on licensing intentions hurt?
