### ISSUE TITLE
defaults: counts

### ISSUE THREAD

**Issue by zvr** [spdx/spec-parser#12]
in all shapes,
if minCount not present
add
```
	minCount: 0
```

in all shapes,
if maxCount not present
add
```
	maxCount: *
```

**Comment by nirmal-suthar** [comment]
Bump. Resolved.

**Comment by zvr** [comment]
@nirmal-suthar get in the habit of adding a second line in the commit message like:
 `    fixes #12`    or `    closes #12` 
so that issues are closed automatically when commits are merged.
