### ISSUE TITLE
Generated Markdown contains multiple consecutive blank lines

### ISSUE THREAD

**Issue by bact** [spdx/spec-parser#120]
Currently, Markdown generated from [the templates](https://github.com/spdx/spec-parser/tree/main/spec_parser/templates/mkdocs) contains multiple consecutive blank lines, which is against markdownlint rule [MD012](https://github.com/DavidAnson/markdownlint/blob/main/doc/md012.md).

Coordinated adjustments among template files can avoid this undesirable outcome.

Proposal:
- Remove explicit multiple consecutive blank lines from every files
- Remove blank lines at the start and the end of the content of `block meta` in every templates that extend from `page.md.j2`, as necessary blank lines are for the blocks is already in `page.md.j2`.
- Remove blank lines at the end of the content of `block meta` in every templates that extend from `page.md.j2`, as necessary blank lines are for the blocks is already in `page.md.j2`.
- Remove blank lines 22 and 23 in `page.md.j2` to leave no blank lines between `block metadata` and `block extra`.
  - This is to avoid two consecutive blank lines at the end of the file, the case that `block extra` is empty.
  - Because of this, it has to maintain that the first line of `block extra` in every templates has to be a blank line (which all of them already are), so that content from `block metadata` and `block extra` will be separated by exactly one blank line, if `block extra` is exist.
- Carefully, with `if` condition block in mind, maintain one blank line before and after a heading/a list. To maintain [M022](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md022.md) and [MD032](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md032.md).

**Comment by zvr** [comment]
I see no issue with having the generated mkdocs input that no one ever sees not conform to some random linter.

I definitely prefer having whitespace that helps editing and understanding in the templates.
