### ISSUE TITLE
Generate External properties restrictions

### ISSUE THREAD

**Issue by zvr** [spdx/spec-parser#125]
The "External properties restrictions" section in classes is not being generated.

Simply recording this, in case anyone is surprised.

**Comment by bact** [comment]
I'm trying to play around this and now having a code to generate these:

![Screenshot 2024-06-30 at 01 26 27](https://github.com/spdx/spec-parser/assets/128572/7466ba94-4667-42bb-bc58-3e27970a4f6a)

![Screenshot 2024-06-30 at 01 25 56](https://github.com/spdx/spec-parser/assets/128572/b4a6f4a1-9649-46b4-a951-1b7d36add878)

The code is [here](https://github.com/bact/spec-parser/tree/add-ext-prop-restrictions) and if you think it can be any use, I can open an PR for review. Thank you.

**Comment by zvr** [comment]
Thanks, @bact ; I have already taken care of it (in a very similar manner). 

I'll leave this open till the changes are merged in main.

**Comment by bact** [comment]
Cool 🎉
