### ISSUE TITLE
[SPDX 3.0.1] NamedIndividual applied rdfs:range and owl:sameAs

### ISSUE THREAD

**Issue by ilans** [spdx/spec-parser#141]
@zvr 
In the ttl of 3.0.1:
```
ns1:NoAssertionElement a owl:NamedIndividual,
        ns1:Element ;
    rdfs:comment """An Individual Value for Element representing a set of Elements of unknown
identify or cardinality (number)."""@en ;
    rdfs:range ns1:Element ;
    owl:sameAs ns1:NoAssertionElement .

ns1:NoneElement a owl:NamedIndividual,
        ns1:Element ;
    rdfs:comment """An Individual Value for Element representing a set of Elements with
cardinality (number/count) of zero."""@en ;
    rdfs:range ns1:Element ;
    owl:sameAs ns1:NoneElement .
```

AFAIK, `rdfs:range` should be applied only on properties, not on class instances.
And another issue, you're applying owl:sameAs using the subject it it applied to:
`ns1:NoneElement owl:sameAs ns1:NoneElement`

Were these intentional?

**Comment by zvr** [comment]
You are correct @ilans , thanks!

- There shouldn't be a `range` there; we already have an `a`
- I should check whether the IRI specified against the generated one, and omit `sameAs` if they are the same
