### ISSUE TITLE
"@type" for Elements is "@vocab" where it should be "@id" in the context file

### ISSUE THREAD

**Issue by goneall** [spdx/spec-parser#143]
Attached is the output of the spec-parser run against the current SPDX 3 model: 
[spdx-context.jsonld.txt](https://github.com/user-attachments/files/16802931/spdx-context.jsonld.txt)

It looks like this may have been introduced with commit https://github.com/spdx/spec-parser/commit/bbe267d950dc3e1dd9694797b6eda8e2d1dd4794

**Comment by goneall** [comment]
Ping @JPEWdev - I'll do some more debugging, but if you happen to see the issue, please comment.

**Comment by JPEWdev** [comment]
This is intentional so that it picks up global named individuals. AFAIK, @vocab is a superset of @id

**Comment by goneall** [comment]
@JPEWdev - never mind - went back and read the pull request and I now understand the change.  Closing this issue.
