### ISSUE TITLE
Should properties which have a range of Element have a local context @vocab?

### ISSUE THREAD

**Issue by goneall** [spdx/spec-parser#144]
In the current generated context file, most or all of the properties that have a range of `Element` includes a local context `@vocab`.

For example:

```
    "element": {
      "@context": {
        "@vocab": "https://spdx.org/rdf/3.0.1/terms/Core/Element/"
      },
      "@id": "https://spdx.org/rdf/3.0.1/terms/Core/element",
      "@type": "@vocab"
    },
```

All other properties that have a `@context` `@vocab` are enumerations.

Is this intentional?

If so, what is the logic behind having a locally defined `@vocab` for the property?

**Comment by JPEWdev** [comment]
This is intentional to ensure that they can used the "global" named individuals defined in the content file (e.g. NoneElement and NoAssertion)

**Comment by goneall** [comment]
Closed as resolved with the above comment
