### ISSUE TITLE
RDF.type of non-vocabulary named individuals may cause cadinality validation error

### ISSUE THREAD

**Issue by bact** [spdx/spec-parser#153]
## Background

- In post-3.0.0 spec-parser, RDF.type was added to non-vocabulary named individuals, so SHACL can validate that the node is of the correct type (see rational here https://github.com/spdx/spec-parser/pull/135)
- `NoneElement` and `NoAssertionElement` are of type `Element`
- `NoneLicense` and `NoAssertionLicense` are of type `IndividualLicensingInfo` (also subclass of `Element`)

## The issue

- `Element` also requires at least one `creationInfo`
- But none of None* and NoAssertion* have that property set, so the validation failed (see https://github.com/spdx/spdx-spec/actions/runs/10806923739/job/30003235732?pr=1107)

**Comment by goneall** [comment]
I wonder if we need to define an Individual `CreationInfo` and an Individual `Organization` (to be used in the required creator field of `CreationInfo` to be referenced in the Individuals which are of types subclassed from `Element`.

**Comment by bact** [comment]
We could. Maybe something along this line, with mandatory properties.

SpdxCreationInfoV3_0
- created: 2024-09-13T00:00:00Z
- createdBy: https://spdx.dev
- specVersion: 3.0.1

SpdxOrganization
- spdxId: https://spdx.dev

Not sure if we need to keep the name of SpdxCreationInfo individual unique across different versions; but as we have the specVersion inside it, we may need something in the name to differentiate it? This is not my area of expertise.

**Comment by zvr** [comment]
This issue will also appear on every predefined Individual -- namely, all licenses and exceptions defined in the License List.

I am OK with defining an Individual Organization for SPDX (with spdxId https://spdx.org) and re-using it for creator in all of these.

But I don't think we should define (in the model, I mean) a special CreationInfo instance. It's not even an Element. Of course the generated serialization of the Individuals will use something, but there is no need to have it specified anywhere (as long as there is one).

**Comment by bact** [comment]
I have tested pyshacl with this hand-edited [spdx-model.ttl.txt](https://github.com/user-attachments/files/16969973/spdx-model.ttl.txt) and looks like it works.

`SpdxOrganization` is defined and used in creationInfo of those four individuals.

```text
spdx-c:SpdxOrgnization a owl:NamedIndividual,
        spdx-c:Organization ;
    spdx-c:spdxId "https://spdx.dev/" ;
    spdx-c:creationInfo [
        rdf:type spdx-c:CreationInfo ;
        spdx-c:created "2024-09-13T00:00:00Z"^^xsd:dateTimeStamp ;
        spdx-c:createdBy spdx-c:SpdxOrgnization ;
        spdx-c:specVersion "3.0.1"^^xsd:string ;
    ] .

spdx-c:NoneElement a owl:NamedIndividual,
        spdx-c:Element ;
    rdfs:comment """An Individual Value for Element representing a set of Elements with
cardinality (number/count) of zero."""@en ;
    spdx-c:name: "NONE" ;
    spdx-c:creationInfo [
        rdf:type spdx-c:CreationInfo ;
        spdx-c:created "2024-09-13T00:00:00Z"^^xsd:dateTimeStamp ;
        spdx-c:createdBy spdx-c:SpdxOrgnization ;
        spdx-c:specVersion "3.0.1"^^xsd:string ;
    ] .
```

Schema generated from that ttl: [schema.json.txt](https://github.com/user-attachments/files/16970004/schema.json.txt)

**Comment by bact** [comment]
PR #154 proposes to add the above information to RDF.

**Comment by bact** [comment]
`SpdxOrganization` will be created by https://github.com/spdx/spdx-3-model/pull/880

**Comment by bact** [comment]
I think we can close this.

**Comment by goneall** [comment]
Agree - closing the issue
