### ISSUE TITLE
Specify type for the string literals defined in the individuals

### ISSUE THREAD

**Issue by goneall** [spdx/spec-parser#164]
Pyshacl is failing validation due to the type not being `xsd:string` for the comment fields defined in the creationInfo individuals.

For example:

```
ns1:comment "This individual element was defined by the spec."@en ;
```

should be changed to:

```
ns1:comment "This individual element was defined by the spec."^^xsd:string ;
```

Reference https://github.com/spdx/spdx-3-model/issues/936#issuecomment-2525344931.

**Comment by zvr** [comment]
Grrr... stupid typo, instead of it being `rdfs:comment` it's a `ns1:comment` (so in SPDX namespace).
I'll fix it.

**Comment by bact** [comment]
Warn that "ns1" "ns2" etc namespaces are up to rdflib to decided and this order could be changed if the code is updated (for example, we refactor the code or we have new profile).
