### ISSUE TITLE
Use the defined URI for the created by organization for references

### ISSUE THREAD

**Issue by goneall** [spdx/spec-parser#166]
The reference to `ns1:createdBy <https://spdx.org/> ;` as the value of createdBy is failing validation in PyShacl.

Even though the OWL file declares this to be the `sameAs` `ns1:SpdxOrganization`, it is not finding the definition.

This may be due to no reasoner being implemented in the PyShacl.

Change the references from `ns1:createdBy <https://spdx.org/> ;` to `ns1:createdBy ns1:SpdxOrganization` passes validatin.

Reference comment https://github.com/spdx/spdx-3-model/issues/936#issuecomment-2525344931

**Comment by zvr** [comment]
OK, this does not make sense.
I'm thinking that this is a limitation of PyShacl.

We can do the change to circumvent it, but let's try another SHACL tester before to see where the issue is.
