### ISSUE TITLE
Deliverables and Purpose

### ISSUE THREAD

**Issue by nirmal-suthar** [spdx/spec-parser#3]
Docs for deliverables and purpose for this tool

CC: @zvr, Matthew Crawford

**Comment by zvr** [comment]
Thanks for this, @nirmal-suthar.
But the issue itself should simply be: "document...." and the answer can be a text/.md in the repo ;-)

**Comment by zvr** [comment]
Having researched this a little, I propose we do *not* use PLY; it has been abandoned by the author and is not recommended any more. He moved to create a newer version, named SLY.

- [SLY docs](https://sly.readthedocs.io/en/latest/)
- a [conference talk](https://www.youtube.com/watch?v=zJ9z6Ge-vXs) presenting and demonstrating it

**Comment by nirmal-suthar** [comment]
> Having researched this a little, I propose we do _not_ use PLY; it has been abandoned by the author and is not recommended any more. He moved to create a newer version, named SLY.

I am totally with this, just explored sly and should use this instead of ply.
