### ISSUE TITLE
Handle format patterns

### ISSUE THREAD

**Issue by zvr** [spdx/spec-parser#47]
New section on input:

```
## Format

- pattern: some-regex-string
```

**Comment by meretp** [comment]
To solve this issue we need to adapt the parser so that this additional section is parsed. This would also fix the CI in the spdx-3-model. 
I am wondering where to put the information on the format? Is there a way to define a format pattern in SHACL?

**Comment by zvr** [comment]
@meretp , yes exactly the same way you specify `sh:maxCount: 1`, you can also say `sh:pattern "some-regex"`

**Comment by zvr** [comment]
Handled in new parser
