### ISSUE TITLE
Explore doc generation

### ISSUE THREAD

**Issue by zvr** [spdx/spec-parser#48]
See whether https://github.com/lambdamusic/Ontospy can be used: it seems to read RDF and generate docs.

Documentation at http://lambdamusic.github.io/Ontospy/

**Comment by meretp** [comment]
I tried Ontospy and generated a html documentation from the generated `model.ttl`. The generated docs can be found here:
https://meretp.github.io/spdx-3-model/index.html

I think this looks really promising. One issue I will try to figure out is why the table in the `Usage` section for each class is not filled properly. 

This is the command I used to generate the docs:
`ontospy gendocs -o generated_docs --type 2 --title SPDX-3.0 ../spec-parser/md_generated/model.ttl`

**Comment by meretp** [comment]
To fill the usage section with the corresponding properties in each class we need to add the `Domain` to each property in the generated ttl file. The information on which `Domain` needs to be added to which `Property` is given in the respecitve `Class` markdown file, we only need to add this information to the properties, I'll try to implement this.

**Comment by zvr** [comment]
This should be moved to https://github.com/spdx/spdx-spec , which generates everything visible.
