### ISSUE TITLE
Values are parsed as lists instead of single values

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spec-parser#55]
I noticed that metadata and properties values (which can only take a single value each) are represented as lists in the parsed `spec`object. For example like this:
```
"properties": {
          "begin": {
            "type": [
              "xsd:positiveInteger"
            ],
            "minCount": [
              "1"
            ],
            "maxCount": [
              "1"
            ]
          },
          "end": {
            "type": [
              "xsd:positiveInteger"
            ],
            "minCount": [
              "1"
            ],
            "maxCount": [
              "1"
            ]
          }
        }
```
or this:
```
"metadata": {
          "name": [
            "SemVer"
          ],
          "SubclassOf": [
            "xsd:string"
          ],
          "Instantiability": [
            "Concrete"
          ],
          "Status": [
            "Stable"
          ],
          "id": [
            "https://spdx.org/rdf/Core/SemVer"
          ]
        }
```
Is this a bug or a feature? I don't see the benefit of it, as there can't be more than one `maxCount`, `minCount`, or `type`.

**Comment by zvr** [comment]
Are all values single for every case, or do we ever have multiple ones?

**Comment by armintaenzertng** [comment]
Currently, there are no list-valued properties in the md-files. If there will ever be any, we can still think about special logic for them then.

**Comment by zvr** [comment]
OK, then it should be easy.

Let's have a PR about "all AV values are single, not lists".
It will only change all `_values = split(...)` to `_values = ...` (but keep the `strip()`).

Shall I do it or will you?

**Comment by armintaenzertng** [comment]
OK, I'll take care of it :)
