### ISSUE TITLE
Some arrows in the generated puml are pointing in the wrong direction

### ISSUE THREAD

**Issue by maxhbr** [spdx/spec-parser#91]
I think that all `<|--` arrows should point in the other direction `--|>`
![2024-01-24_23-17-42](https://github.com/spdx/spec-parser/assets/1187050/0adf0dbc-33c0-4dbb-b24b-ccfe8010d4c2)

**Comment by zvr** [comment]
You are correct, @maxhbr. I'll fix this.

**Comment by zvr** [comment]
Fixed in https://github.com/spdx/spec-parser/commit/2e8a8c6942810af732a461dd107e63e43cdc87ed
